name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}/csvparser/CsvParser.csproj
    - name: Build
      run: dotnet Build ${{ github.workspace }}/csvparser/CsvParser.csproj --no-restore --verbosity normal
    - name: Test
      run: dotnet test ${{ github.workspace }}/csvparserTests/CsvParserTests.csproj --no-build --verbosity normal
